### ISSUE TITLE
Build a `Advanced developer` section documentaiton

### ISSUE THREAD

**Issue by santanaluiz** [archway-network/archway-docs#71]
## Description

We need to build a section to support more advanced developers and how can we enable them to better use our tools

## TODO

- [x] Page 1: What is archway cli really?
- [x] Page 2: What is archwayd really?
- [x] Page 3: How to debug smart contracts
- [x] Troubleshooting guide
